SET ECHO OFF
SET TERMOUT OFF
SET FEEDBACK OFF
SET WRAP OFF
SET PAGESIZE 0
SET LINESIZE 10000
SET ARRAYSIZE 5000
SET NUMW 30
SET TRIMSPOOL ON
SET UNDERLINE OFF
SET RECSEP OFF
SET VERIFY OFF
SET COLSEP '|'


SPOOL '&1'

ALTER SESSION SET nls_date_format = 'YYYY-MM-DD HH24:MI:SS';

SELECT * FROM &1;

SPOOL OFF